# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_try', models.IntegerField()),
                ('username', models.CharField(max_length=500)),
                ('organizationID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PreferenceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodID', models.IntegerField()),
                ('ID_try', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.MainTable')),
            ],
        ),
    ]
