# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-11 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20160509_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizationID', models.IntegerField()),
                ('organizationName', models.CharField(max_length=500)),
            ],
        ),
    ]
