# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-12 11:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_userextradetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditemtable',
            name='foodID',
        ),
        migrations.RemoveField(
            model_name='organizationtable',
            name='organizationID',
        ),
        migrations.AlterField(
            model_name='maintable',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preferencetable',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
