# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-12 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20160512_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencetable',
            name='foodID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.FoodItemTable'),
        ),
    ]
