# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-14 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_auto_20160512_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintable',
            name='userID',
        ),
        migrations.DeleteModel(
            name='MainTable',
        ),
    ]
